apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: development
commonLabels:
  app: testapp-dev
  develper: elkadeem
  managed-by: WaelElkadeem
resources:
  - ../../base

patches:
  - path: deployment-dev.yaml
  - path: service-dev.yaml

configMapGenerator:
  - name: configmap-dev
    literals:
      - UserName=elkadeem
      - ConnectionString=connectionstring

secretGenerator:
  - name: secrets-dev
    literals:
      - username=elkadeem
      - password=P@ssw0rd#@$
generatorOptions:
  disableNameSuffixHash: true
  labels:
    app: app-dev
    develper: elkadeem

vars:
  - name: Servcie_Name
    objref:
      name: web-service      
      kind: Service
      apiVersion: v1